version: "3"

services:
    app:
        container_name: grpc
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        tty: true
        ports:
            - "9000:9000"
        command: ./main
        volumes:
            - ./:/go/src/work
            - /var/run/docker.sock:/var/run/docker.sock